[book]
title = "Data Engineering Book"
authors = ["Rojesh Shikhrakar"]
language = "en"

[output.html.playground]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.tabs]

[output.html]
mathjax-support = true
additional-css = ["theme/tabs.css"]
additional-js  = ["theme/tabs.js"]